apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: redis-cart
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - redis-cart.hipstershop-prod.public.demo.keptn.sh
  - redis-cart
  http:
  - route:
    - destination:
        host: redis-cart.hipstershop-prod.svc.cluster.local
