apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: currencyservice-primary
spec:
  ports:
  - name: grpc
    port: 7000
    targetPort: 7000
  selector:
    app: currencyservice-primary
  type: ClusterIP
status:
  loadBalancer: {}
