apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: adservice-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice-primary
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: adservice-primary
    spec:
      containers:
      - env:
        - name: DT_CUSTOM_PROP
          value: keptn_project=hipstershop keptn_service=adservice keptn_stage=hardening
            keptn_deployment=primary
        - name: PORT
          value: "9555"
        image: gcr.io/dynatrace-demoability/awsadservice:45c069f
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:9555
          initialDelaySeconds: 20
          periodSeconds: 15
        name: server
        ports:
        - containerPort: 9555
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:9555
          initialDelaySeconds: 20
          periodSeconds: 15
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 180Mi
      imagePullSecrets:
      - name: regcred
      terminationGracePeriodSeconds: 5
status: {}
