apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: adservice-primary
spec:
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555
  selector:
    app: adservice-primary
  type: ClusterIP
status:
  loadBalancer: {}
