apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: adservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - adservice.hipstershop-hardening.public.demo.keptn.sh
  - adservice
  http:
  - route:
    - destination:
        host: adservice-canary.hipstershop-hardening.svc.cluster.local
    - destination:
        host: adservice-primary.hipstershop-hardening.svc.cluster.local
      weight: 100
