apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: productcatalogservice-primary
spec:
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550
  selector:
    app: productcatalogservice-primary
  type: ClusterIP
status:
  loadBalancer: {}
