apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: emailservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - emailservice.hipstershop-prod.public.demo.keptn.sh
  - emailservice
  http:
  - route:
    - destination:
        host: emailservice-canary.hipstershop-prod.svc.cluster.local
    - destination:
        host: emailservice-primary.hipstershop-prod.svc.cluster.local
      weight: 100
