apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: cartservice-primary
spec:
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070
  selector:
    app: cartservice-primary
  type: ClusterIP
status:
  loadBalancer: {}
