apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: checkoutservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - checkoutservice.hipstershop-hardening.public.demo.keptn.sh
  - checkoutservice
  http:
  - route:
    - destination:
        host: checkoutservice-canary.hipstershop-hardening.svc.cluster.local
      weight: 100
    - destination:
        host: checkoutservice-primary.hipstershop-hardening.svc.cluster.local
