apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  creationTimestamp: null
  name: checkoutservice-primary
spec:
  host: checkoutservice-primary.hipstershop-prod.svc.cluster.local
