apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: checkoutservice-primary
spec:
  ports:
  - name: grpc
    port: 5050
    targetPort: 5050
  selector:
    app: checkoutservice-primary
  type: ClusterIP
status:
  loadBalancer: {}
