apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: paymentservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - paymentservice.hipstershop-hardening.public.demo.keptn.sh
  - paymentservice
  http:
  - route:
    - destination:
        host: paymentservice-canary.hipstershop-hardening.svc.cluster.local
      weight: 100
    - destination:
        host: paymentservice-primary.hipstershop-hardening.svc.cluster.local
