apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: paymentservice-primary
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: paymentservice-primary
  type: ClusterIP
status:
  loadBalancer: {}
