apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: shippingservice-canary
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: shippingservice
  type: ClusterIP
status:
  loadBalancer: {}
