apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: shippingservice-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice-primary
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: shippingservice-primary
    spec:
      containers:
      - env:
        - name: DT_CUSTOM_PROP
          value: keptn_project=hipstershop keptn_service=shippingservice keptn_stage=prod
            keptn_deployment=primary
        - name: PORT
          value: "50051"
        image: gcr.io/dynatrace-demoability/awsshippingservice:45c069f
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50051
        name: server
        ports:
        - containerPort: 50051
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50051
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      imagePullSecrets:
      - name: regcred
status: {}
