apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  creationTimestamp: null
  name: shippingservice-canary
spec:
  host: shippingservice-canary.hipstershop-prod.svc.cluster.local
