apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: shippingservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - shippingservice.hipstershop-prod.public.demo.keptn.sh
  - shippingservice
  http:
  - route:
    - destination:
        host: shippingservice-canary.hipstershop-prod.svc.cluster.local
    - destination:
        host: shippingservice-primary.hipstershop-prod.svc.cluster.local
      weight: 100
