apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: recommendationservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - recommendationservice.hipstershop-prod.public.demo.keptn.sh
  - recommendationservice
  http:
  - route:
    - destination:
        host: recommendationservice-canary.hipstershop-prod.svc.cluster.local
    - destination:
        host: recommendationservice-primary.hipstershop-prod.svc.cluster.local
      weight: 100
