apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: recommendationservice-canary
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  selector:
    app: recommendationservice
  type: ClusterIP
status:
  loadBalancer: {}
