apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: recommendationservice-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice-primary
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: recommendationservice-primary
    spec:
      containers:
      - env:
        - name: DT_CUSTOM_PROP
          value: keptn_project=hipstershop keptn_service=recommendationservice keptn_stage=prod
            keptn_deployment=primary
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: productcatalogservice:3550
        - name: ENABLE_PROFILER
          value: "0"
        image: gcr.io/dynatrace-demoability/awsrecommendationservice:45c069f
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:8080
          periodSeconds: 5
        name: server
        ports:
        - containerPort: 8080
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:8080
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 450Mi
          requests:
            cpu: 100m
            memory: 220Mi
      imagePullSecrets:
      - name: regcred
      terminationGracePeriodSeconds: 5
status: {}
